version: "3.5"

services:
  traefik:
    image: traefik:2.0-alpine
    restart: always
    container_name: traefik
    networks:
      - webnsurf
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/config:/etc/traefik

networks:
  webnsurf:
    name: webnsurf_network
